version: '3.8'

services:
  tf_example:
    build:
      context: .
      dockerfile: Dockerfile_tf
    volumes:
      - ./code:/rfl/code
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command: jupyter lab --notebook-dir=/rfl/code --ip 0.0.0.0 --no-browser --allow-root

  torch_example:
    build:
      context: .
      dockerfile: Dockerfile_torch
    volumes:
      - ./code:/rfl/code
    ports:
      - "8889:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command: jupyter lab --notebook-dir=/rfl/code --ip 0.0.0.0 --no-browser --allow-root