# Use the official Python image from the Docker Hub
FROM nvcr.io/nvidia/tensorflow:24.07-tf2-py3

COPY requirements_tf.txt /tmp/
RUN pip install --requirement /tmp/requirements_tf.txt
# Specify the command to run Jupyter Notebook within the container
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root"]